FROM dustynv/ros:humble-ros-base-l4t-r36.3.0

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    ROS_DISTRO=humble

# Common tools 
COPY docker/scripts/install-common.sh /tmp/install-common.sh
RUN chmod +x /tmp/install-common.sh && /tmp/install-common.sh && rm /tmp/install-common.sh

ENV NVM_DIR=/root/.nvm

WORKDIR /root
